sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 #deactivate prompts because we can't access it in travis
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d #decript gcloud token to e readable and connect to gcloud
  - curl https://sdk.cloud.google.com | bash > /dev/null; # install gcloud cli
  - source $HOME/google-cloud-sdk/path.bash.inc # adds gcloud to path
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json # use the decripted fil to connect to account
  # !!!! Do the three next commands in the gcloud console before doing the first deployment and generate the secrets if some are used
  - gcloud config set project formation-kubernetes-394517 # set the project to use by its id
  - gcloud config set compute/zone northamerica-northeast1-a # sets the zone that we chose when creating the kubernetes cluster on gcloud
  - gcloud container clusters get-credentials formation-kubernetes-cluster # which cluster to use when usin Kubernetes commands
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin #to login to docker with the variable set in travis
  - docker build -t shicknventive/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shicknventive/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
