apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sarahick-com-tls
spec:
  secretName: sarahick-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sarahick.com
  dnsNames:
    - sarahick.com
    - www.sarahick.com
